apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: change_me_locally
  JWT_SECRET: change_me_jwt_secret
  RABBITMQ_URL: amqp://admin:change_me_locally@rabbitmq-service:5672
  DATABASE_URL: postgresql://mlm_user:change_me_locally@postgres-service:5432/dakdam_db
